left_leg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_hip_yaw
    - left_hip_roll
    - left_hip_pitch
    - left_knee
    - left_ankle_pitch
    - left_ankle_roll
  gains:
    left_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_leg_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_hip_yaw
    - right_hip_roll
    - right_hip_pitch
    - right_knee
    - right_ankle_pitch
    - right_ankle_roll
  gains:
    right_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_shoulder_pitch
    - right_shoulder_roll
    - right_shoulder_twirl
    - right_elbow_pitch
    - right_hand_twirl
    - right_finger_pitch
  gains:
    right_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_shoulder_pitch
    - left_shoulder_roll
    - left_shoulder_twirl
    - left_elbow_pitch
    - left_hand_twirl
    - left_finger_pitch
  gains:
    left_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
left_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_hand_twirl
    - left_finger_pitch
  gains:
    left_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - right_hand_twirl
    - right_finger_pitch
  gains:
    right_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
legs_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pelvis
    - left_hip_yaw
    - left_hip_roll
    - left_hip_pitch
    - left_knee
    - left_ankle_pitch
    - left_ankle_roll
    - right_hip_yaw
    - right_hip_roll
    - right_hip_pitch
    - right_knee
    - right_ankle_pitch
    - right_ankle_roll
  gains:
    pelvis:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arms_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - left_shoulder_pitch
    - left_shoulder_roll
    - left_shoulder_twirl
    - left_elbow_pitch
    - left_hand_twirl
    - left_finger_pitch
    - right_shoulder_pitch
    - right_shoulder_roll
    - right_shoulder_twirl
    - right_elbow_pitch
    - right_hand_twirl
    - right_finger_pitch
  gains:
    left_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
torso_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pelvis
  gains:
    pelvis:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
whole_body_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_yaw
    - head_pitch
    - left_shoulder_pitch
    - left_shoulder_roll
    - left_shoulder_twirl
    - left_elbow_pitch
    - left_hand_twirl
    - left_finger_pitch
    - pelvis
    - left_hip_yaw
    - left_hip_roll
    - left_hip_pitch
    - left_knee
    - left_ankle_pitch
    - left_ankle_roll
    - right_hip_yaw
    - right_hip_roll
    - right_hip_pitch
    - right_knee
    - right_ankle_pitch
    - right_ankle_roll
    - right_shoulder_pitch
    - right_shoulder_roll
    - right_shoulder_twirl
    - right_elbow_pitch
    - right_hand_twirl
    - right_finger_pitch
  gains:
    head_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    head_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    pelvis:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    left_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hip_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_knee:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_ankle_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_roll:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_shoulder_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_elbow_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_hand_twirl:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    right_finger_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
head_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - head_yaw
    - head_pitch
  gains:
    head_yaw:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    head_pitch:
      p: 100
      d: 1
      i: 1
      i_clamp: 1