controller_list:
  - name: left_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee
      - left_ankle_pitch
      - left_ankle_roll
  - name: right_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle_pitch
      - right_ankle_roll
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_shoulder_twirl
      - right_elbow_pitch
      - right_hand_twirl
      - right_finger_pitch
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_shoulder_twirl
      - left_elbow_pitch
      - left_hand_twirl
      - left_finger_pitch
  - name: left_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_hand_twirl
      - left_finger_pitch
  - name: right_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - right_hand_twirl
      - right_finger_pitch
  - name: legs_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - pelvis
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee
      - left_ankle_pitch
      - left_ankle_roll
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle_pitch
      - right_ankle_roll
  - name: arms_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_shoulder_twirl
      - left_elbow_pitch
      - left_hand_twirl
      - left_finger_pitch
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_shoulder_twirl
      - right_elbow_pitch
      - right_hand_twirl
      - right_finger_pitch
  - name: torso_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - pelvis
  - name: whole_body_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - head_yaw
      - head_pitch
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_shoulder_twirl
      - left_elbow_pitch
      - left_hand_twirl
      - left_finger_pitch
      - pelvis
      - left_hip_yaw
      - left_hip_roll
      - left_hip_pitch
      - left_knee
      - left_ankle_pitch
      - left_ankle_roll
      - right_hip_yaw
      - right_hip_roll
      - right_hip_pitch
      - right_knee
      - right_ankle_pitch
      - right_ankle_roll
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_shoulder_twirl
      - right_elbow_pitch
      - right_hand_twirl
      - right_finger_pitch
  - name: head_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - head_yaw
      - head_pitch